# Generated by Django 5.1 on 2024-08-29 11:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('symbol', models.CharField(max_length=5)),
                ('price', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lastupdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('slug', models.SlugField(max_length=250, unique_for_date='published')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='stockpredictor.category')),
            ],
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=6, max_digits=9)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='stockpredictor.stock')),
            ],
        ),
    ]
