# Generated by Django 5.1 on 2024-08-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockpredictor', '0003_alter_stock_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='data',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.TextField(null=True),
        ),
    ]
