# Generated by Django 5.1 on 2024-08-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockpredictor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ('-lastupdate',)},
        ),
        migrations.RemoveField(
            model_name='stock',
            name='active',
        ),
        migrations.AddField(
            model_name='stock',
            name='status',
            field=models.CharField(choices=[('on', 'On'), ('off', 'Off')], default='on', max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='on'),
        ),
    ]
